name: Cross-Platform Build

on:
  push:
    branches:
      - feature/build-actions
    tags:
      - 'v1.0.0'  # Triggers on any tag pus

jobs:
  build_on_windows:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: windows-node-${{ hashFiles('/package-lock.json') }}
          restore-keys: |
            windows-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --prefer-offline --legacy-peer-deps || exit 0  # Error handling

      - name: Build the Package
        run: npm run package

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: windows-installer-ia32-setup
          path: release/build/LibreLinkUpDesktop-0.1.13-ia32-setup.exe # Adjust the path based on actual output
          overwrite: true
          
  build_on_ubuntu:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: ubuntu-node-${{ hashFiles('/package-lock.json') }}
          restore-keys: |
            ubuntu-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --prefer-offline --legacy-peer-deps

      - name: Build the Package
        run: npm run package

      - name: Upload Ubuntu Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ubuntu-installer-appimage
          path: release/build/LibreLinkUpDesktop-0.1.13-x86_64.AppImage # Adjust path based on actual output
          overwrite: true

  build_on_mac:
    runs-on: macOS-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Cache Node.js dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: mac-node-${{ hashFiles('/package-lock.json') }}
          restore-keys: |
            mac-node-

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install --prefer-offline --legacy-peer-deps

      - name: Build the Package
        run: npm run package

      - name: Upload macOS Artifact
        uses: actions/upload-artifact@v4
        with:
          name: mac-installer-x64
          path: release/build/LibreLinkUpDesktop-0.1.13-x64.dmg  # Adjust path based on actual output
          overwrite: true
